# constants.py
MAGIC_COOKIE = 0xabcddcba

# Message types
OFFER_MESSAGE_TYPE = 0x2
REQUEST_MESSAGE_TYPE = 0x3
PAYLOAD_MESSAGE_TYPE = 0x4

# Ports
UDP_PORT = 8080
TCP_PORT = 8081
BROADCAST_PORT = 8082

# Payload sizes
UDP_PAYLOAD_SIZE = 1024
TCP_PAYLOAD_SIZE = 1024

# Timeouts
UDP_TIMEOUT = 1
TCP_TIMEOUT = 10

PAYLOAD_FORMAT = "!I B Q Q"
OFFER_FORMAT = "!I B H H"
REQ_FORMAT = '!I B Q'
